app:
  security:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
  minio:
    bucket: ${MINIO_BUCKET}
    url: ${MINIO_URL}
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
  database-access-type: jpa

spring:
  application:
    name: filesharing
  datasource:
    url: jdbc:postgresql://localhost:5432/filesharing
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

api:
  version: 1.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui
  override-with-generic-response: false