CREATE TABLE files (
	id BIGSERIAL PRIMARY KEY,
	filename VARCHAR(255) NOT NULL,
	storage_key VARCHAR(512) NOT NULL UNIQUE,
	size_bytes BIGINT NOT NULL,
	upload_date TIMESTAMP NOT NULL DEFAULT NOW(),
	is_public BOOLEAN NOT NULL DEFAULT FALSE,
	owner_id BIGINT NOT NULL,
	CONSTRAINT fk_files_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);